### ISSUE TITLE
QtCreator 4.0.0 cannot read both sketch and C++ template

### ISSUE THREAD

**Issue by j8asic** [cleitonsouza01/qt-creator-arduino#1]
It seems that QtCreator 4.0.0 (under Arch Linux) cannot read both types of templates: sketch and C++. When both are inside "wizards" folder, it shows on C++ type of template. After deleting C++ wizard folder, sketch template is properly shown.

Edit: It can be solved by renaming IDs within wizard.xml, e.g. in sketch template folder:
id="A.ArduinoSketch"

Best regards,
Josip

**Comment by cleitonsouza01** [comment]
Thanks Josip, I will follow your tip, fix it and update here soon.

**Comment by good-vi** [comment]
Thanks! Now QtCreator 4.2.1 show me all position, but it still not compile.

**Comment by good-vi** [comment]
I solve problem. In my Qt Creator 4.2.1 isn't work you build properties. I did it by hand)
