### ISSUE TITLE
Headers problem

### ISSUE THREAD

**Issue by rebelC0der** [cleitonsouza01/qt-creator-arduino#2]
Hi. This is very useful thing, but it does not work for me unfortunately. 

I have tried with Arduino 1.6.9 and Arduino 1.6.3 (what you used) and there is header issue:

```
/home/jurisl/Downloads/arduino-1.6.3/hardware/arduino/avr/cores/arduino/Arduino.h:28:
error: avr/pgmspace.h: No such file or directory
#include <avr/pgmspace.h>
#include <avr/io.h>
#include <avr/interrupt.h>
...
```

I have added direct path to these headers, which are in a different folder, then where your wizard is looking for them, but there are tons more errors poping up.

`#include "pins_arduino.h"  // is missing too`

Pointing .pro file directly to a folder where this header is, generates tons more ERRORS.

Are you planing to update this wizard to latest qt-creator/Arduino IDE version?

Regards.
Juris.

**Comment by cleitonsouza01** [comment]
Hello RebelCoderRU, thanks for you comments. The project receive contribution from ViktorKovalev3. Please, see now works for you.
